### ISSUE TITLE
Add me as a maintainer

### ISSUE THREAD

**Issue by kaneoriley** [hubot-archive/hubot-ingress#79]
Project looks a bit neglected, potentially interested in helping maintain it.

(Title reworded to shut up gitmagic-bot)

**Comment by therealklanni** [comment]
I definitely appreciate the help. I no longer maintain it myself, I generally leave it to @sleavitt and @EvoldicA as the current maintainers. Please coordinate with them as best as you can.

We may want to consider moving any activity to the original repo [therealklanni/hubot-ingress](https://github.com/therealklanni/hubot-ingress) since the hubot org folks are trying to move away from hosting scripts on hubot-scripts. Let me know and I will get you 3 added as collabs on that repo and we can freeze/deprecate this one.

For some reason when I try to add @lennykano to the collaborators, it says you're not a GitHub member. Is your profile private or something?

**Comment by lennykano** [comment]
Hi. All sounds good to me. I'm not sure why it wouldn't let you add me, my profile is public and I haven't set any restrictions that I'm aware of :/

**Comment by therealklanni** [comment]
Yeah, strange. I also just tried adding @sleavitt to the therealklanni/hubot-ingress repo, and neither of your usernames show up when I attempt it.

However, adding you by email address seems to work.

**Comment by therealklanni** [comment]
I sent each of you a collab invite to the original repo.

**Comment by EvoldicA** [comment]
Welcome Lenny kano, and thanks for the invite to the original repo!
